In [22]:
import numpy as np

In [23]:
# a. Create a null vector of size 10 but the fifth value which is 1
a = np.zeros(10)
a[4] = 1
print(a)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [24]:
# b. Create a vector with values ranging from 10 to 49
b = np.arange(10, 50)
print(b)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
# c. Reverse a vector (first element becomes last)
c = b[::-1]
print(c)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [26]:
# d. Create a 3x3 matrix with values ranging from 0 to 8
d = np.arange(9).reshape(3,3)
print(d)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
# e. Find indices of non-zero elements from [1,2,0,0,4,0]
e = np.array([1,2,0,0,4,0])
print(np.nonzero(e))


(array([0, 1, 4]),)


In [28]:
# f. Create a random vector of size 30 and find the mean value
f = np.random.rand(30)
print(f.mean())


0.5458063755018934


In [29]:
# g. Create a 2d array with 1 on the border and 0 inside
g = np.ones((5,5))
g[1:-1,1:-1] = 0
print(g)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
# h. Create a 8x8 matrix and fill it with a checkerboard pattern
h = np.zeros((8,8))
h[1::2,::2] = 1
h[::2,1::2] = 1
print(h)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
# i. Create a checkerboard 8x8 matrix using the tile function
i0 = np.tile([0.,1.],4)
i1 = np.tile([1.,0.],4)
i = np.tile([i0,i1],(4,1))
print(i, i.shape)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]] (8, 8)


In [34]:
# j. Given a 1D array, negate all elements which are between 3 and 8, in place
Z = np.arange(11)
print(Z)
Z[(Z > 3) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [35]:
# k. Create a random vector of size 10 and sort it
Z = np.random.random(10)
print(Z)
Z = np.sort(Z)
print(Z)

[0.03765546 0.21371224 0.56108011 0.0962133  0.18916884 0.6622775
 0.86883292 0.55904895 0.74499044 0.4859332 ]
[0.03765546 0.0962133  0.18916884 0.21371224 0.4859332  0.55904895
 0.56108011 0.6622775  0.74499044 0.86883292]


In [44]:
# l. Consider two random array A anb B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = (A == B).all()
print("A:", A)
print("B:", B)
print("Are A and B equal?", equal)

A: [1 0 1 0 1]
B: [1 0 1 1 0]
Are A and B equal? False


In [47]:
# m. How to calculate the square of every number in an array in place (without creating temporaries)?
Z = np.arange(10, dtype=np.int32)
print(Z.dtype, Z)
Z **= 2
print(Z.dtype, Z)

int32 [0 1 2 3 4 5 6 7 8 9]
int32 [ 0  1  4  9 16 25 36 49 64 81]


In [49]:
# n. How to get the diagonal of a dot product?
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A, B)
D = np.diag(C)
print(D)

[ 18  66 132]
